// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaperWork.Api.Data;

#nullable disable

namespace PaperWork.Api.Migrations
{
    [DbContext(typeof(PaperWorkDbContext))]
    [Migration("20251023224839_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaperWork.Api.Entitty.PaperWorkEntity", b =>
                {
                    b.Property<string>("PWId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActionDecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionOwnerManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionOwnerManagerFeedbackDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionOwnerManagerRegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CBACodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Directorate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeRegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackChannel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GettingStartedGeneralDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PWId");

                    b.ToTable("HR_Feedback_Process");
                });
#pragma warning restore 612, 618
        }
    }
}
