// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaperWork.Api.Data;

#nullable disable

namespace PaperWork.Api.Migrations
{
    [DbContext(typeof(PaperWorkDbContext))]
    [Migration("20251024000153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PaperWork.Api.Entitty.PaperWorkEntity", b =>
                {
                    b.Property<string>("PWId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ActionDecision")
                        .HasColumnType("longtext");

                    b.Property<string>("ActionOwnerManager")
                        .HasColumnType("longtext");

                    b.Property<string>("ActionOwnerManagerFeedbackDetail")
                        .HasColumnType("longtext");

                    b.Property<string>("ActionOwnerManagerRegistrationNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("CBACodes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Directorate")
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeRegistrationNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("FeedbackChannel")
                        .HasColumnType("longtext");

                    b.Property<string>("FeedbackDetail")
                        .HasColumnType("longtext");

                    b.Property<string>("FeedbackType")
                        .HasColumnType("longtext");

                    b.Property<string>("GettingStartedGeneralDescription")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Month")
                        .HasColumnType("longtext");

                    b.Property<string>("Year")
                        .HasColumnType("longtext");

                    b.HasKey("PWId");

                    b.ToTable("HR_Feedback_Process");
                });
#pragma warning restore 612, 618
        }
    }
}
